- 👋 Hi, I’m @FOOSTYMAMA1988 INCORPORATED BY ONDARASIE2024
- 👀 I’m interested in DEVELOPING ANIMATED NFT'S...
- 🌱 I’m currently learning ADVANCE SOFTWARE DEVELOPMENT...
- 💞️ I’m looking to collaborate on INVESTORS, DEVELOPERS DESIGNERS WEB AND FASHION CREATE TEAM MEMBERS...
- 📫 How to reach me MAKE YOURSELF AVAILABLE TO ME ...
- 😄 Pronouns:WOMAN,HURT,WORKING, REBUILDING LOVING KIND AVAILABLE WILLING LOOKING LEARNING...
- ⚡ Fun fact:LIFE WORKS FOR THOSE WHO ARE WORKING ALL WORK IS NOT MEANT TO BE SEEN
- SO WORK IS TO BE DONE WITHIN...

<!---
ONDARASIE2024/ONDARASIE2024 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
